/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.JOptionPane;

/**
 *
 * @author Lorenzo Windmoller
 */
public class IPV6_Hex_Dcm extends javax.swing.JFrame {

    /**
     * Creates new form IPV6_Hex_Dcm
     */
    public IPV6_Hex_Dcm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bt_avancar = new javax.swing.JButton();
        bt_menu = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(34, 139, 34));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(34, 139, 34));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 139, 34));
        jLabel2.setText("CONVERSÃO DE IPV4");

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 139, 34));
        jLabel1.setText("Lorenzo Windmoller Martins");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 139, 34));
        jLabel3.setText("Hexadecimal --> Decimal");

        bt_avancar.setBackground(new java.awt.Color(112, 128, 144));
        bt_avancar.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        bt_avancar.setText("AVANÇAR");
        bt_avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_avancarActionPerformed(evt);
            }
        });

        bt_menu.setBackground(new java.awt.Color(112, 128, 144));
        bt_menu.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        bt_menu.setText("MENU");
        bt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menuActionPerformed(evt);
            }
        });

        bt_sair.setBackground(new java.awt.Color(112, 128, 144));
        bt_sair.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        bt_sair.setText("SAIR");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 139, 34));
        jLabel4.setText("Informe endereço IPV6:");

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("OCR A Extended", 3, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(34, 139, 34));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 139, 34)));

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 139, 34));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_avancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_avancar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_avancarActionPerformed
        
        jLabel5.setText("");
        String ipv6 = jTextField1.getText();
        boolean verif = true;
        String str = "";
        int aux;
        int x=0,y=0,i,j,a=0,b=0;
        
        for(i=0;i<ipv6.length()-1;i++){
            if(ipv6.charAt(i)==':'&&ipv6.charAt(i+1)==':')a++;
        }
        if(ipv6.charAt(ipv6.length()-2)==':'&&ipv6.charAt(ipv6.length()-1)==':'&&a>1)verif = false;
        if(a>1)verif = false;
        
        if(ipv6.length()>39||ipv6.length()<3)verif = false;
        for(i=0;i<ipv6.length();i++){
            if(ipv6.charAt(i)!='0'&&
                    ipv6.charAt(i)!='1'&&
                    ipv6.charAt(i)!='2'&&
                    ipv6.charAt(i)!='3'&&
                    ipv6.charAt(i)!='4'&&
                    ipv6.charAt(i)!='5'&&
                    ipv6.charAt(i)!='6'&&
                    ipv6.charAt(i)!='7'&&
                    ipv6.charAt(i)!='8'&&
                    ipv6.charAt(i)!='9'&&
                    ipv6.charAt(i)!='A'&&
                    ipv6.charAt(i)!='B'&&
                    ipv6.charAt(i)!='C'&&
                    ipv6.charAt(i)!='D'&&
                    ipv6.charAt(i)!='E'&&
                    ipv6.charAt(i)!='F'&&
                    ipv6.charAt(i)!='a'&&
                    ipv6.charAt(i)!='b'&&
                    ipv6.charAt(i)!='c'&&
                    ipv6.charAt(i)!='d'&&
                    ipv6.charAt(i)!='e'&&
                    ipv6.charAt(i)!='f'&&
                    ipv6.charAt(i)!=':')verif = false;
            if(ipv6.charAt(i)!=':'){
                if(x==0)b++;
                x++;
            }
            else x=0;
            if(ipv6.charAt(i)==':')y++;
            if(x>4)verif = false;
        }
        if(y<2||y>7)verif = false;
        if(a==0&&y>b)verif = false;
        if(b<8&&a==0)verif = false;
        if(ipv6.charAt(ipv6.length()-1)==':'&&ipv6.charAt(ipv6.length()-2)!=':')verif = false;
     
        if(!verif){
            JOptionPane.showMessageDialog(rootPane,"Endereço Inválido\nInforme novamente","ALERTA",JOptionPane.WARNING_MESSAGE);
            jTextField1.setText("");
        }
        else{
            String newipv6 = "", strr = "";
            
            str = "";
            aux=0;
            
            for(i=0;i<ipv6.length();i++){
                
                if(ipv6.charAt(i)!=':'){
                    str += ipv6.charAt(i);
                }
                else if(ipv6.charAt(i)==':'&&i!=0){
                    if(ipv6.charAt(i-1)!=':'){
                        for(j=str.length()-1;j>=0;j--){
                            strr += str.charAt(j);
                        }
                        for(j=0;j<strr.length();j++){
                            if(strr.charAt(j)=='A'||strr.charAt(j)=='a')aux += Math.pow(16, j)*10;
                            else if(strr.charAt(j)=='B'||strr.charAt(j)=='b')aux += Math.pow(16, j)*11;
                            else if(strr.charAt(j)=='C'||strr.charAt(j)=='c')aux += Math.pow(16, j)*12;
                            else if(strr.charAt(j)=='D'||strr.charAt(j)=='d')aux += Math.pow(16, j)*13;
                            else if(strr.charAt(j)=='E'||strr.charAt(j)=='e')aux += Math.pow(16, j)*14;
                            else if(strr.charAt(j)=='F'||strr.charAt(j)=='f')aux += Math.pow(16, j)*15;
                            else aux += Math.pow(16, j)*Integer.parseInt(String.valueOf(strr.charAt(j)));
                        }
                        newipv6 += Integer.toString(aux);
                    }
                    newipv6 += ':';
                    str = "";
                    strr = "";
                    aux=0;
                }
                else{
                    newipv6 += ':';
                }
            }
            if(ipv6.charAt(ipv6.length()-1)!=':'){
                for(j=str.length()-1;j>=0;j--){
                    strr += str.charAt(j);
                }
                for(j=0;j<strr.length();j++){
                    if(strr.charAt(j)=='A'||strr.charAt(j)=='a')aux += Math.pow(16, j)*10;
                    else if(strr.charAt(j)=='B'||strr.charAt(j)=='b')aux += Math.pow(16, j)*11;
                    else if(strr.charAt(j)=='C'||strr.charAt(j)=='c')aux += Math.pow(16, j)*12;
                    else if(strr.charAt(j)=='D'||strr.charAt(j)=='d')aux += Math.pow(16, j)*13;
                    else if(strr.charAt(j)=='E'||strr.charAt(j)=='e')aux += Math.pow(16, j)*14;
                    else if(strr.charAt(j)=='F'||strr.charAt(j)=='f')aux += Math.pow(16, j)*15;
                    else aux += Math.pow(16, j)*Integer.parseInt(String.valueOf(strr.charAt(j)));
                }
                newipv6 += Integer.toString(aux);
            }
            
            jLabel5.setText(newipv6);
            
        }
        
    }//GEN-LAST:event_bt_avancarActionPerformed

    private void bt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menuActionPerformed
        new Main_Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_menuActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPV6_Hex_Dcm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPV6_Hex_Dcm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPV6_Hex_Dcm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPV6_Hex_Dcm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IPV6_Hex_Dcm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_avancar;
    private javax.swing.JButton bt_menu;
    private javax.swing.JButton bt_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
